image: python:3.13

stages:
 - build
 - test

# For debugging
before_script:
  - python --version
  - pip --version  
  - pip install --upgrade pip

build:
  stage: build
  script:
    - pip install -r requirements.txt

dependency_check:
  stage: test
  script:
    - python main.py --cli

unit_test:
  stage: test
  script:
    - echo "Test temporarily disabled"

lint: # For parallel execution
  stage: test
  script:
    - flake8 .
