image: python:3.13

stage:
    - build
    - test

# For debugging
before_script:
  - python --version
  - pip --version  
  - pip install --upgrade pip


build:
    stage: build
    script:
      - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest
